### ISSUE TITLE
object /path/to/pinned/map: no such file or directory

### ISSUE THREAD

**Issue by FOSquare** [cloudflare/xdpcap#10]
Hello, I am new to eBPF. After I run 
xdpcap /path/to/pinned/map dump.pcap "tcp and port 80"
I have the below errors.

Error setting locked memory limit: operation not permitted
Error: creating filter: loading hook map: object /path/to/pinned/map: no such file or directory

I do not understand where is the path to pinned map? could you provide me an example? Thanks a lot. Why I also has the locked memory limit? 

go version go1.12.5 linux/amd64

Thanks a lot.

**Comment by lmb** [comment]
Hi!

The "locked memory limit" error is because the program tries to raise a resource limit, but fails since you're not using `sudo`. See https://blog.cloudflare.com/epbf_sockets_hop_distance/#so_attach_bpftoruletheworld for a little bit of context.

`/path/to/pinned/map` is meant as an example. You have to use `xdpcap` in conjuction with an XDP program that you are running. Have you seen https://github.com/cloudflare/xdpcap#instrumentation in the manual?

**Comment by lmb** [comment]
P.S. If you are new to eBPF, https://www.collabora.com/news-and-blog/blog/2019/04/05/an-ebpf-overview-part-1-introduction/ might be a good place to start.

**Comment by FOSquare** [comment]
Thanks so much for your answer.
I read the instrumentation several times. I could not get the points before. I knew /path/to/pinned/map is am example. 

Now I am clear a little bit.

I find xdp_hook.c in the directory of  ~/Golang/src/github.com/cloudflare/xdpcap/testdata.

Shall I first cd into the folder, then run sudo xdpcap xdp_hook.c dump.pcap "tcp and port 80" ??

But I find that "sudo: xdpcap: command not found" 
without sudo it works. should I install go and xdpcap under the root account?

Thanks so much.

**Comment by lmb** [comment]
Maybe you can tell me what you are trying to achieve? `xdpcap` is not useful out of the box right now, you need an XDP program to go with it. That isn't provided in this repo, you need to write one yourself.

**Comment by FOSquare** [comment]
I want to test the caputring speed that xdpcap can achieve? wireshark achieves around 1Gbps. netmap is at around 6 Gbps. I am curious wherther xdpcap can achieve 10Gbps or even higher such as 40Gbps. Thanks.

**Comment by lmb** [comment]
Ah, I see. I think it's better if you think of `xdpcap` as an introspection tool for XDP programs, it's not in any way meant to be faster than other options. I'll defer this to @arthurfabre, but from my POV your use case is out of scope for us.

**Comment by FOSquare** [comment]
Thank you so much. My felling is that xdp can achieve much faster perfomance. 
Your suggesiton provides me with a good start, thanks agian.
