### ISSUE TITLE
The captured packet length is 1518?

### ISSUE THREAD

**Issue by FOSquare** [cloudflare/xdpcap#24]
I run iperf on two servers. and the packet length of the flow is in the range of 1500~65536 bytes.

However, with wireshark I can observer the maximum packet length of the captured packet is 1518 bytes of the files caputred by xdpcap. 

with another captured tool. I could find that packet length is not a fixed value 1518. 

Does xdpcap change the packet header? otherwise, the packet length should be the initial value between 1500 ~ 65536, rather than 1518 

Thanks.

**Comment by arthurfabre** [comment]
`xdpcap` doesn't change the packet header. A `1518` byte packet sounds a lot like a `1500` byte MTU: `14` (ethernet) + `4` (vlan) + `1500` (payload).

It's possible that the receiving side is somehow reassembling the packets, are you using something like [LRO](https://en.wikipedia.org/wiki/Large_receive_offload)?

**Comment by FOSquare** [comment]
No.
But for the iperf, I generate 10 connections to reach a high bandwidth.
