### ISSUE TITLE
How is packet data actually written to userspace?

### ISSUE THREAD

**Issue by Lekensteyn** [cloudflare/xdpcap#28]
Consider this eBPF program:
https://github.com/cloudflare/xdpcap/blob/31c7d91ee43e4922302b627370df61438ce20b97/cmd/xdpcap/program.go#L130-L151

It roughly translates to:
```c
struct {
    u64 action;
    u64 packet_length;
} data = { ..., len };
bpf_perf_event_output(ctx, map, (len << 32) | BPF_F_CURRENT_CPU,
                      &data, sizeof(data));
```

These events are consumed here:
https://github.com/cloudflare/xdpcap/blob/31c7d91ee43e4922302b627370df61438ce20b97/cmd/xdpcap/filter.go#L152-L166

How did the packet data (`struct xdp_md::data`) end up in the BPF map? I did not run the code, but manually reviewed it in order to understand how it works. What am I missing?

The question was prompted by a proposal to add dedicated helpers for packet capture:
https://lkml.kernel.org/r/1567892444-16344-1-git-send-email-alan.maguire@oracle.com

**Comment by arthurfabre** [comment]
> How did the packet data (struct xdp_md::data) end up in the BPF map?

The perf map only holds metadata for a perf event ring buffer, the `perf_event_output_helper` writes the packet contents as a perf event (in that ring buffer).

**Comment by marshalWS** [comment]
Hi, by the way.
Did you test the capturing speed of xdpcap.? How? 
 Here is my question.
link>>> .... #39
