### ISSUE TITLE
Does Packets captured by xdpcap  go across Protocol stack

### ISSUE THREAD

**Issue by marshalWS** [cloudflare/xdpcap#33]
Does Packets captured by xdpcap  go across Protocol stack?
Thanks !

**Comment by arthurfabre** [comment]
What do you mean by Protocol stack?

**Comment by marshalWS** [comment]
thanks for reply!
Is packet follow the red arrow?
 
![_20191209221016](https://user-images.githubusercontent.com/33886493/70443424-1753a200-1ad3-11ea-8d21-ff242919676b.jpg)

**Comment by marshalWS** [comment]
> What do you mean by Protocol stack?

As i known ,for example bpf byte can be set by raw_socket,  which can filter link layer packets.
. So this filter type is by protocol stack?

**Comment by marshalWS** [comment]
I got it. 
Packets captured by xdpcap tool  before skb.
