### ISSUE TITLE
Error: creating filter: loading hook map: get object /path/to/pinned/map: permission denied

### ISSUE THREAD

**Issue by marshalWS** [cloudflare/xdpcap#35]
I exec  ` sudo ./xdpcap /path/to/pinned/map   dump.pcap "tcp and port 80" `,  after i  copy xdp_hook.c.elf  to  /path/to/pinned/map . Then raise a  error: 
"Error: creating filter: loading hook map: get object /path/to/pinned/map: permission denied"

**Comment by arthurfabre** [comment]
`/path/to/pinned/map` needs to be a pinned eBPF map, not an ELF. You need to load the eBPF ELF you want to instrument in the kernel (eg with [libbpf](https://github.com/libbpf/libbpf) or [cilium/ebpf](https://github.com/cilium/ebpf)), and pin the tail map to a [bpffs](https://cilium.readthedocs.io/en/v1.1/kubernetes/install/#admin-mount-bpffs).

[xdp-tutorial](https://github.com/xdp-project/xdp-tutorial/) has some good getting started with XDP examples, with loader and libbpf.

**Comment by arthurfabre** [comment]
For example https://github.com/xdp-project/xdp-tutorial/tree/master/basic04-pinning-maps shows how to pin eBPF maps

**Comment by marshalWS** [comment]
> For example https://github.com/xdp-project/xdp-tutorial/tree/master/basic04-pinning-maps shows how to pin eBPF maps

thanks very much. I get it.

**Comment by marshalWS** [comment]
close
