### ISSUE TITLE
Does xdpcap work similarly to xdpdump, where it can capture packets before and after xdp program execution?

### ISSUE THREAD

**Issue by yzhao1012** [cloudflare/xdpcap#50]
https://github.com/xdp-project/xdp-tools
https://www.redhat.com/en/blog/capturing-network-traffic-express-data-path-xdp-environment

Has another tool called xdpdump. It was built around ebpf as well, specifically:
```
xdpdump to capture the original packet at ingress and the modifications the XDP program has made to the packet after execution
```
Is this the same for xdpcap?

**Comment by arthurfabre** [comment]
Unfortunately not, currently `xdpcap` only supports capturing the packet after the program has run. #51 tracks adding support for this.
