### ISSUE TITLE
Would this be possible to use with redbpf? 

### ISSUE THREAD

**Issue by Synkstar** [cloudflare/xdpcap#54]
Rust is a language I've been interested in for awhile but I aint very good at it 2bh. But if stuff like this would be possible to use in that I might think of using it over c because i'm not that good at that either and rust can be used for much more other things that I would want to do. Thanks.

**Comment by lmb** [comment]
You can use the same approach that this repo follows with your redbpf code. We won't add support for rust user space to this repo however.
